import type { NextPage } from 'next'
import Head from 'next/head'
import BlogTiles from "../components/BlogTitles/BlogTiles";
import styles from './styles/Home.module.scss';
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import {props, BlogObjInterface} from "./Interfaces/Interface";
import { getAllBlogs, getFooterData, getNavData } from './api/apiCalls';
import { useDataContext } from './context/dataContext';

const Home: NextPage<props> = (content) => {
    const {arr, navData, footerData} = content;
    const { setNav, setFooter } = useDataContext();
    setNav(navData);
    setFooter(footerData);

    const blogArr = arr;

    return (
      <div className={styles.blogContainer}>
        <Head>
            <title>Blog Rendering</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar data={navData}/>
        {
            blogArr.map((item) => (
              <BlogTiles key={item.uid} item={item}/>
          ))
        }
        <Footer data={footerData}/>
      </div>
    )
}

export default Home;


export async function getServerSideProps(){

  const stack = await getAllBlogs();
  const navData = await getNavData();
  const footerData = await getFooterData();
    
  const arr: BlogObjInterface[] = [];

  stack[0].map((item: any)=> {
    let obj = {
      author: item.author_details.authorname,
      blogimage: item.blogimage.url,
      createdat: item.createdat,
      title: item.title,
      uid: item.uid,
    }
    arr.push(obj);
  })
  
  if (!stack[0]) {
    alert("Data cannot be fetched");
    return; 
  }
  
  return {
    props: {arr, navData, footerData}
  }
}




